-- AlterTable
ALTER TABLE "Order" ADD COLUMN "exchangeRate" DOUBLE PRECISION NOT NULL DEFAULT 0;
ALTER TABLE "Order" ADD COLUMN "usdtRate" DOUBLE PRECISION NOT NULL DEFAULT 0;

-- AlterTable
ALTER TABLE "OrderItem" ADD COLUMN "costUSDT" DOUBLE PRECISION;
ALTER TABLE "OrderItem" ADD COLUMN "yoniEnabled" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "OrderItem" ADD COLUMN "yoniType" TEXT NOT NULL DEFAULT 'percentage';
ALTER TABLE "OrderItem" ADD COLUMN "yoniValue" DOUBLE PRECISION NOT NULL DEFAULT 25;
ALTER TABLE "OrderItem" ADD COLUMN "shippingCost" DOUBLE PRECISION NOT NULL DEFAULT 0;
ALTER TABLE "OrderItem" ADD COLUMN "profitType" TEXT NOT NULL DEFAULT 'percentage';
ALTER TABLE "OrderItem" ADD COLUMN "profitValue" DOUBLE PRECISION NOT NULL DEFAULT 0;
