ALTER TABLE "Admin" ADD COLUMN "role" TEXT NOT NULL DEFAULT 'admin';

ALTER TABLE "OrderItem" ADD COLUMN "costUSDT" REAL;
ALTER TABLE "OrderItem" ADD COLUMN "yoniEnabled" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "OrderItem" ADD COLUMN "yoniType" TEXT NOT NULL DEFAULT 'percentage';
ALTER TABLE "OrderItem" ADD COLUMN "yoniValue" REAL NOT NULL DEFAULT 25;
ALTER TABLE "OrderItem" ADD COLUMN "shippingCost" REAL NOT NULL DEFAULT 0;
ALTER TABLE "OrderItem" ADD COLUMN "profitType" TEXT NOT NULL DEFAULT 'percentage';
ALTER TABLE "OrderItem" ADD COLUMN "profitValue" REAL NOT NULL DEFAULT 0;
ALTER TABLE "OrderItem" ADD COLUMN "finalPriceUSD" REAL;
ALTER TABLE "OrderItem" ADD COLUMN "finalPriceARS" REAL;

ALTER TABLE "Bulk" ADD COLUMN "internalNumber" INTEGER;
ALTER TABLE "Bulk" ADD COLUMN "date" TEXT;
ALTER TABLE "Bulk" ADD COLUMN "products" TEXT;
ALTER TABLE "Bulk" ADD COLUMN "createdAt" TEXT;
ALTER TABLE "Bulk" ADD COLUMN "updatedAt" TEXT;

ALTER TABLE "Product" ADD COLUMN "createdAt" TEXT;
ALTER TABLE "Product" ADD COLUMN "updatedAt" TEXT;
ALTER TABLE "Product" ADD COLUMN "finalPriceUSD" REAL;
ALTER TABLE "Product" ADD COLUMN "finalPriceARS" REAL;
ALTER TABLE "Product" ADD COLUMN "categoryId" TEXT;
ALTER TABLE "Product" ADD COLUMN "distributorId" TEXT;
